spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# 암호화 설정
app:
  encryption:
    master-key: ${MASTER_ENCRYPTION_KEY:a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456}


market-data:
  kis: ## 한국투자증권
    enabled: true
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ENC(ASeLjrVsngF75xUe5V7rd7P6uMxohHxFjrvAih4fKyPG4mxMw0TbrRhahtbBBUzuc/HmmHdNYCENk78L4sMiHA==)
    app-secret: ENC(Wu7f5NX4BhO8QwL7D6+eHI5EOo99sdF0Vmg/ZMFoYS52ShLhVVFV+Y7vk96rTkM9aguiPDWnhfG/q15Z6OsR4FPQiZuF+RpGpkeW2P4R6D/WGFX7RWunP+C+fXgC3mysYh7MbOtbm0sxGXsrtss/0ZlVBcnzmrG24nWTBrV1qGt7l9Yku9LZbM6+MHUkfmBkZLR4e3yzI9PsT32aJpQd1GiROOvShRPEFeZx5ZBSCr7s2vmnvXqQtIHyGpcdvf+V/eNQLtB5m1bDmV/OILdxD+wzDYnIRxl0)

  alpha-vantage:
    enabled: false
    base-url: https://www.alphavantage.co/query
    api-key: ${ALPHA_VANTAGE_API_KEY}

  bok: ## Bank of Korea
    enabled: false
    base-url: https://ecos.bok.or.kr
    api-key: ${BOK_API_KEY}

# 이벤트 감지 설정
event-detection:
  enabled: false
  thresholds:
    price-spike-percent: 5.0    # 5% 이상 급등
    price-drop-percent: -5.0    # 5% 이상 급락
    volume-surge-ratio: 2.0     # 평균 대비 200% 이상
  scheduler:
    interval: 30s               # 30초마다 감지

# 로깅 설정
logging:
  level:
    me.rgunny.event: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    me.rgunny.event: INFO

---
# 운영 환경
spring:
  config:
    activate:
      on-profile: prod
