spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    
    # MongoDB 설정
    mongodb:
      uri: mongodb://${MONGO_USERNAME:marketpulse_user}:${MONGO_PASSWORD:marketpulse_pass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:marketpulse}?authSource=${MONGO_DATABASE:marketpulse}
      auto-index-creation: true

# 암호화 설정
app:
  encryption:
    master-key: ${MASTER_ENCRYPTION_KEY:a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456}


market-data:
  kis: ## 한국투자증권
    enabled: true
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ENC(bAI2B9y4YYc7jKZEOhk8cmZxG2RqXjfNIKzThRR8M7w88ZDEJ1cOYsGlzjuSRUhfV9fle4sV858+lVdj6oJcwg==)
    app-secret: ENC(GkUPL4rT6hAAJGHeQpgjEcPaDCw1CD3zL2e5WJkyHmXkXxFO045WND+k07AFNhw9rLfQezBlsOnISWIcnCqlIb9C/ycg2bT1Gkok2UH5HxfrDMD+B7zcMD7s9JC4AiIqMV33zmvUcMjNtmlFiWRcJkZj+XI9zMAQvmPP4pIvuj866LRA0qOh0NGcGZZC8NJyfiJ9e4KVfxzaFQ4s2e/zQQq4cKbxYMkBptiCgTtuOOockGe92lz1QUiepulTSwwEnVhc+z2dxiezojqsGcfDtg==)
    
    # API 경로 설정
    stock-price-transaction-id: FHKST01010100
    grant-type: client_credentials
    token-path: /oauth2/tokenP
    stock-price-path: /uapi/domestic-stock/v1/quotations/inquire-price
    health-path: /oauth2/tokenP
    
    # 헤더 설정
    headers:
      transaction-id: tr_id
      continuation-key: tr_cont
      cust-type: custtype
      personal-customer-type: P
      content-type: application/json; charset=utf-8
    
    # 타임아웃 설정
    timeouts:
      connection-timeout-seconds: 10
      read-timeout-seconds: 30
      write-timeout-seconds: 30
      response-timeout-seconds: 60

  alpha-vantage:
    enabled: false
    base-url: https://www.alphavantage.co/query
    api-key: ${ALPHA_VANTAGE_API_KEY}

  bok: ## Bank of Korea
    enabled: false
    base-url: https://ecos.bok.or.kr
    api-key: ${BOK_API_KEY}


# MarketPulse 알림 설정
marketpulse:
  alert:
    price:
      rise-threshold: 5.0         # 급등 알림 임계값 (%)
      fall-threshold: -5.0        # 급락 알림 임계값 (%)
      limit-up-threshold: 29.5    # 상한가 알림 임계값 (%)
      limit-down-threshold: -29.5 # 하한가 알림 임계값 (%)

# 이벤트 감지 설정 (Legacy - 향후 제거 예정)
event-detection:
  enabled: false
  thresholds:
    price-spike-percent: 5.0    # 5% 이상 급등
    price-drop-percent: -5.0    # 5% 이상 급락
    volume-surge-ratio: 2.0     # 평균 대비 200% 이상
  scheduler:
    interval: 30s               # 30초마다 감지

# gRPC 클라이언트 설정
grpc:
  client:
    notification:
      address: 'static://localhost:9082'
      negotiationType: plaintext

# 로깅 설정
logging:
  level:
    me.rgunny.event: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    me.rgunny.event: INFO

---
# 운영 환경
spring:
  config:
    activate:
      on-profile: prod
