# ========================================
# Event Detection Service Configuration
# ========================================

spring:
  application:
    name: event-detection
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본값: local
  config:
    import: classpath:application-common.yml  # Common 인프라 설정 import

server:
  port: 8081

# ===== KIS API 설정 =====
market-data:
  kis:
    enabled: true
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ${KIS_APP_KEY:ENC(7EqZ9Egni4PWW66duuwbe7kLu05QmxalIxJw+UX9MkS5XH7q28cFZOyHmVuBm8IO0ilXgly9G3px4CRZ+3lgscEgaV9BF5qEBwFXpMej7kw=)}
    app-secret: ${KIS_APP_SECRET:ENC(Qh1nvFGTzpjBTxMCgJaaPEWn0ONWEDYpnrxU8g9KoBFqcFJ53sQVUQ6219nh+K4j1SEch7bCSaHlKFxFtqadsj0WF+Wpk661XhuGEbU39lASR/f10WuDqwrHJImzPn1xl5dstTo0pYJIrZT/PbW7WPH6AVTykbUC2wuQ92lU7yArQ7TfXAfulhtw8OY7noAXznJjrNlWDLCx8RGzAuHJJz01N7qZQPzpAZoVv1LQnBhLoZdZApC4hnym+zluzrrb)}
    
    # API 경로 설정
    stock-price-transaction-id: FHKST01010100
    stock-master-transaction-id: CTPF1702R
    grant-type: client_credentials
    token-path: /oauth2/tokenP
    stock-price-path: /uapi/domestic-stock/v1/quotations/inquire-price
    stock-master-path: /uapi/domestic-stock/v1/quotations/search-info
    health-path: /oauth2/tokenP
    
    # 시장별 상품 코드
    market-product-codes:
      kospi: "300"
      kosdaq: "301"
      konex: "302"
    
    # 헤더 설정
    headers:
      transaction-id: tr_id
      continuation-key: tr_cont
      cust-type: custtype
      personal-customer-type: P
      content-type: application/json; charset=utf-8
    
    # 타임아웃 설정
    timeouts:
      connection-timeout-seconds: 10
      read-timeout-seconds: 30
      write-timeout-seconds: 30
      response-timeout-seconds: 60

# ===== MarketPulse 비즈니스 설정 =====
marketpulse:
  # 알림 임계값
  alert:
    price:
      rise-threshold: 5.0         # 급등 알림 임계값 (%)
      fall-threshold: -5.0        # 급락 알림 임계값 (%)
      limit-up-threshold: 29.5    # 상한가 알림 임계값 (%)
      limit-down-threshold: -29.5 # 하한가 알림 임계값 (%)
  
  # 종목 마스터 동기화 설정
  stock-master:
    sync:
      enabled: false                      # 동기화 활성화
      mode: INCREMENTAL                   # 기본 동기화 모드
      full-sync-cron: "0 0 2 * * *"      # 전체 동기화: 매일 새벽 2시
      incremental-sync-cron: "0 0 * * * *" # 증분 동기화: 매시간
      kospi-sync-cron: "0 0 3 * * *"     # KOSPI 동기화: 매일 새벽 3시
      kosdaq-sync-cron: "0 30 3 * * *"   # KOSDAQ 동기화: 매일 새벽 3시 30분
      batch-size: 100                    # 배치 처리 크기
      batch-delay-ms: 100                # 배치 간 지연 (밀리초)
      api-timeout-seconds: 30            # API 타임아웃
      max-retry-attempts: 3              # 최대 재시도 횟수
      kospi-sync-enabled: false          # KOSPI 개별 동기화
      kosdaq-sync-enabled: false         # KOSDAQ 개별 동기화
      failure-threshold: 10.0            # 실패 임계값 (%)
      notification-enabled: true         # 결과 알림

# ===== gRPC 클라이언트 설정 =====
grpc:
  client:
    notification:
      address: 'static://localhost:9082'
      negotiationType: plaintext