name: Refactoring Task
description: 구조 개선, 성능 최적화, 코드 정리 등
title: "[Refactor] "
labels: ["refactor"]
body:
  - type: textarea
    id: reason
    attributes:
      label: 💡 리팩토링 이유
      description: 어떤 이유로 리팩토링이 필요한가요?
  - type: textarea
    id: scope
    attributes:
      label: ✂️ 영향 범위
      placeholder: service layer 전체, 특정 모듈 등
  - type: textarea
    id: checklist
    attributes:
      label: ✅ 작업 항목
      value: |
        - [ ] 코드 수정
        - [ ] 테스트 통과 확인
        - [ ] 기능 영향도 확인
