# ========================================
# Watchlist Service Configuration
# ========================================
server:
  port: 8084

spring:
  application:
    name: watchlist
  profiles:
    active: local
    include: kafka
  datasource:
    url: jdbc:mysql://localhost:3307/watchlist
    username: watchlist
    password: watchlist123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      lifecycle-management: start_only
      file: ./watchlist/docker-compose.yml
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

kafka:
  enabled: true

watchlist:
  kafka:
    topic: watchlist.events

resilience4j:
  circuitbreaker:
    enabled: false
