# ========================================
# Notification Service - Local Profile
# ========================================

# 로깅 레벨
logging:
  level:
    me.rgunny.marketpulse.notification: DEBUG
    me.rgunny.marketpulse.common: DEBUG
    io.grpc: INFO

