# ========================================
# Notification Service Configuration
# ========================================

spring:
  application:
    name: notification
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본값: local
  config:
    import: classpath:application-common.yml  # Common 인프라 설정 import

server:
  port: 8082

# ===== gRPC Server 설정 =====
grpc:
  server:
    port: 9082

# ===== 알림 채널 설정 =====
notification:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
  
  # 기본 수신자 설정
  default:
    recipient: ${NOTIFICATION_DEFAULT_RECIPIENT:market-alerts}