services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: watchlist
      MYSQL_USER: watchlist
      MYSQL_PASSWORD: watchlist123
    ports:
      - "3307:3306"  # 3307로 설정하여 다른 모듈과 충돌 방지
    volumes:
      - watchlist-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  watchlist-mysql-data: